import React, {useEffect, useState} from 'react';
import {Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';

const API = 'http://10.0.2.2:8081';
const colors = {navy:'#102A43', blue:'#2367A6', gold:'#B77A08', muted:'#65758A', bg:'#F7F9FC', green:'#18794E'};

async function request(path, options={}, token) {
  const response = await fetch(`${API}${path}`, {headers:{'Content-Type':'application/json', ...(token ? {Authorization:`Bearer ${token}`} : {}), ...(options.headers||{})}, ...options});
  const body = await response.json().catch(()=>({}));
  if (!response.ok) throw new Error(body.detail || `Request failed (${response.status})`);
  return body;
}

function Logo(){return <View style={styles.logo}><Image source={require('./assets/faceattend-logo.png')} style={styles.logoImage}/><Text style={styles.logoText}>FaceAttend</Text></View>}
function Button({title,onPress,secondary=false}){return <Pressable onPress={onPress} style={[styles.button,secondary&&styles.secondary]}><Text style={[styles.buttonText,secondary&&{color:colors.blue}]}>{title}</Text></Pressable>}
function Card({children}){return <View style={styles.card}>{children}</View>}
function Login({onLogin}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <View style={styles.center}><Logo/><Text style={styles.title}>Welcome back</Text><Text style={styles.subtitle}>Sign in with your authorized account.</Text><TextInput placeholder="Student ID / username" value={username} onChangeText={setUsername} style={styles.input} autoCapitalize="none"/><TextInput placeholder="Password" value={password} onChangeText={setPassword} style={styles.input} secureTextEntry/><Text style={styles.error}>{error}</Text><Button title={busy?'Signing in…':'Login'} onPress={async()=>{setBusy(true);setError('');try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({username,password})});await AsyncStorage.setItem('session',JSON.stringify(data));onLogin(data)}catch(e){setError(e.message)}finally{setBusy(false)}}}/></View>}
function Stat({value,label}){return <Card><Text style={styles.stat}>{value}</Text><Text style={styles.muted}>{label}</Text></Card>}
function StudentHome({session}){const [data,setData]=useState(null);const [error,setError]=useState('');useEffect(()=>{let live=true;const load=async()=>{try{setData(await request('/student/attendance/overview',{},session.access_token));setError('')}catch(e){if(live)setError(e.message)}};load();const timer=setInterval(load,15000);return()=>{live=false;clearInterval(timer)}},[]);const present=data?.summary?.present||0;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>FACEATTEND</Text><Text style={styles.header}>Attendance overview</Text><Card><Text style={styles.muted}>STUDENT</Text><Text style={styles.cardTitle}>{data?.profile?.name||session.user.username}</Text><Text style={styles.muted}>Student ID: {data?.profile?.student_id||session.user.student_id||'—'}</Text></Card>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.row}><Stat value={`${data?.summary?.overall_percentage||0}%`} label="Overall attendance"/><Stat value={present} label="Present days"/></View><Text style={styles.section}>Attendance records</Text>{data?.attendance?.length?data.attendance.map((x,i)=><Card key={i}><Text style={styles.cardTitle}>Present</Text><Text style={styles.muted}>{x.timestamp||'Recorded'} · {x.session_id||'Attendance session'}</Text></Card>):<Card><Text style={styles.muted}>No attendance records found.</Text></Card>}</ScrollView>}
function AdminHome({session}){return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>FACEATTEND</Text><Text style={styles.header}>Administration</Text><Card><Text style={styles.cardTitle}>Manage the attendance workspace</Text><Text style={styles.muted}>Add students, monitor attendance, and manage schedules from the web/API-connected app.</Text></Card><Button title="Add student" onPress={()=>Alert.alert('Student registration','Use the teacher/admin registration workflow to enter Student ID, name, email, phone, date of birth, program, and face photos.')}/><Button title="Users and attendance" secondary onPress={()=>Alert.alert('Coming next','The Expo migration foundation is ready; full admin navigation is being connected next.')}/></ScrollView>}
function TeacherHome({session}){return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>FACEATTEND</Text><Text style={styles.header}>Teacher dashboard</Text><Card><Text style={styles.cardTitle}>Authorized attendance tools</Text><Text style={styles.muted}>Register students and run face attendance sessions.</Text></Card><Button title="Register student" onPress={()=>Alert.alert('Student registration','Enter the student details and capture the guided face photos.')}/><Button title="Start attendance" secondary onPress={()=>Alert.alert('Attendance','Camera attendance flow will use the secure recognition API.')}/></ScrollView>}
function App(){const [session,setSession]=useState(null);useEffect(()=>{AsyncStorage.getItem('session').then(x=>x&&setSession(JSON.parse(x)))},[]);if(!session)return <><StatusBar style="dark"/><Login onLogin={setSession}/></>;const home=session.user.role==='student'?<StudentHome session={session}/>:session.user.role==='teacher'?<TeacherHome session={session}/>:<AdminHome session={session}/>;return <><StatusBar style="dark"/>{home}<View style={styles.footer}><Button title="Log out" secondary onPress={async()=>{await AsyncStorage.removeItem('session');setSession(null)}}/></View></>}

const styles=StyleSheet.create({center:{flex:1,backgroundColor:'#fff',padding:28,justifyContent:'center'},page:{padding:22,paddingBottom:40,backgroundColor:colors.bg,flexGrow:1},logo:{flexDirection:'row',alignItems:'center',marginBottom:32},logoImage:{width:58,height:58,borderRadius:16},logoText:{color:colors.navy,fontSize:24,fontWeight:'800',marginLeft:10},title:{fontSize:30,fontWeight:'800',color:colors.navy},subtitle:{color:colors.muted,fontSize:15,marginTop:8,marginBottom:24},input:{borderWidth:1,borderColor:'#D4DDE7',borderRadius:12,padding:15,marginBottom:12,backgroundColor:'#fff'},button:{backgroundColor:colors.blue,borderRadius:12,padding:16,alignItems:'center',marginTop:14},secondary:{backgroundColor:'#EAF2FA'},buttonText:{color:'#fff',fontWeight:'800'},error:{color:'#B42318',minHeight:20,marginTop:4},kicker:{color:colors.gold,fontWeight:'800',fontSize:12},header:{fontSize:30,fontWeight:'800',color:colors.navy,marginTop:5,marginBottom:18},card:{backgroundColor:'#fff',borderRadius:18,padding:18,marginBottom:12,shadowColor:'#102A43',shadowOpacity:.06,shadowRadius:8,elevation:2},cardTitle:{fontSize:17,fontWeight:'800',color:colors.navy,marginBottom:6},muted:{color:colors.muted,fontSize:13},row:{flexDirection:'row',gap:10},stat:{fontSize:28,fontWeight:'800',color:colors.navy},section:{fontSize:19,fontWeight:'800',color:colors.navy,marginVertical:10},footer:{padding:18,backgroundColor:colors.bg}}
);
