import React, {useEffect, useRef, useState} from 'react';
import {Alert, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {CameraView, CameraType, useCameraPermissions} from 'expo-camera';
import axios from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';

const api=axios.create({baseURL:process.env.EXPO_PUBLIC_API_URL||'http://10.0.2.2:8080',timeout:30000});
api.interceptors.request.use(async c=>{const t=await AsyncStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const poses=[['center','Center Face','Look straight at the camera'],['chin_up','Chin Up','Raise your chin slightly'],['chin_down','Chin Down','Lower your chin slightly'],['left','Face Left','Turn your face slightly to the left'],['right','Face Right','Turn your face slightly to the right']];
export default function GuidedRegister({go}:{go:(s:string)=>void}){const [form,setForm]=useState({student_id:'',name:'',email:'',phone:'',date_of_birth:'',program:''}),[step,setStep]=useState(-1),[photos,setPhotos]=useState<Record<string,string>>({}),[permission,requestPermission]=useCameraPermissions(),[cameraReady,setCameraReady]=useState(false),[checking,setChecking]=useState(false),[message,setMessage]=useState('Position your face inside the oval'),[validFrames,setValidFrames]=useState(0),camera=useRef<CameraView>(null),[busy,setBusy]=useState(false);const ready=!!form.student_id.trim()&&!!form.name.trim();const activePose=poses[Math.min(poses.length-1,Math.max(step,0))]||poses[0];const [target,title,hint]=activePose;
 // Keep the native camera warm between poses; only reset pose validation.
 useEffect(()=>{setValidFrames(0);setMessage(cameraReady?'Position your face inside the guide':'Starting camera…')},[step]);
 useEffect(()=>{if(step<0||step>=5||!permission?.granted||!cameraReady||photos[target])return;let alive=true;const check=async()=>{if(!alive||checking||!camera.current)return;setChecking(true);try{const shot=await camera.current.takePictureAsync({quality:.35,skipProcessing:true});if(!shot?.uri)return;const d=new FormData();d.append('target_pose',target);d.append('file',{uri:shot.uri,name:'alignment.jpg',type:'image/jpeg'} as any);const r=(await api.post('/validate-face',d,{headers:{'Content-Type':'multipart/form-data'}})).data;if(r.valid){setMessage('✓ Hold still — capturing automatically');setValidFrames(v=>v+1)}else{setValidFrames(0);setMessage(r.issues?.[0]||'Adjust your position')}}catch(e:any){setMessage(e?.response?.data?.detail||'Could not check the camera frame')}finally{setChecking(false)}};const id=setInterval(check,800);return()=>{alive=false;clearInterval(id)}},[step,target,permission?.granted,cameraReady,photos[target],checking]);
 useEffect(()=>{if(validFrames<1||!camera.current||photos[target])return;camera.current.takePictureAsync({quality:1,skipProcessing:false}).then(x=>{if(x?.uri){setPhotos(p=>({...p,[target]:x.uri}));setMessage('✓ Photo captured')}}).catch(()=>setMessage('Capture failed — please try again'));setValidFrames(0)},[validFrames]);
 const capture=()=>{if(!cameraReady||!camera.current)return;camera.current.takePictureAsync({quality:1}).then(x=>x?.uri&&setPhotos(p=>({...p,[target]:x.uri}))).catch(()=>Alert.alert('Camera error','Hold the phone steady and try again.'))};const submit=async()=>{setBusy(true);try{const d=new FormData();Object.entries(form).forEach(([k,v])=>d.append(k,v));poses.forEach(([k])=>d.append('files',{uri:photos[k],name:`${k}.jpg`,type:'image/jpeg'} as any));await api.post('/register-student',d,{headers:{'Content-Type':'multipart/form-data'}});Alert.alert('Student registered','Five face images enrolled.',[{text:'Done',onPress:()=>go('students')}])}catch(e:any){Alert.alert('Enrollment failed',e?.response?.data?.detail||'Please try again')}finally{setBusy(false)}};
 if(step<0)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>go('home')}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.kicker}>STUDENT MANAGEMENT</Text><Text style={s.h1}>Register student</Text><Text style={s.muted}>Required details unlock face enrollment.</Text>{[['student_id','Student ID / Roll number *'],['name','Full name *'],['email','Email'],['phone','Phone'],['date_of_birth','Date of birth'],['program','Program / course']].map(([k,l])=><View style={s.field} key={k}><Text style={s.label}>{l}</Text><TextInput value={(form as any)[k]} onChangeText={v=>setForm({...form,[k]:v})} style={s.input} placeholderTextColor="#91a0b7"/></View>)}<Pressable disabled={!ready} onPress={()=>setStep(0)} style={[s.button,!ready&&s.disabled]}><Text style={s.buttonText}>Continue to face enrollment</Text></Pressable></ScrollView></SafeAreaView>;
 if(step<5)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>setStep(step-1)}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.kicker}>FACE ENROLLMENT · {step+1}/5</Text><Text style={s.h1}>{title}</Text><Text style={s.muted}>{hint}</Text>{permission?.granted?<View style={s.camera}><CameraView ref={camera} facing={'front' as CameraType} onCameraReady={()=>{setCameraReady(true);setMessage('Align your face inside the oval')}} onMountError={()=>setMessage('Camera could not start. Close other camera apps and retry.')} style={s.preview}/><View style={s.oval}/></View>:<Pressable onPress={requestPermission} style={s.button}><Text style={s.buttonText}>Allow camera access</Text></Pressable>}<Text style={s.guidance}>{photos[target]?'✓ Photo captured':message}</Text><Text style={s.muted}>{checking?'Checking alignment…':cameraReady?'Auto-captures after two valid checks':'Waiting for camera…'}</Text>{photos[target]?<><Pressable onPress={()=>{setPhotos(p=>({...p,[target]:''}));setMessage('Align your face inside the oval')}} style={s.secondary}><Text style={s.secondaryText}>Retake photo</Text></Pressable><Pressable onPress={()=>setStep(step+1)} style={s.button}><Text style={s.buttonText}>{step===4?'Review enrollment':'Continue'}</Text></Pressable></>:<Pressable disabled={!cameraReady} onPress={capture} style={[s.secondary,!cameraReady&&s.disabled]}><Text style={s.secondaryText}>Capture manually</Text></Pressable>}</ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>setStep(4)}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.kicker}>REVIEW · 5/5</Text><Text style={s.h1}>Review photos</Text>{poses.map(([k,t])=><View style={s.row} key={k}><Image source={{uri:photos[k]}} style={s.thumb}/><Text style={s.rowText}>✓ {t}</Text><Pressable onPress={()=>setStep(poses.findIndex(p=>p[0]===k))}><Text style={s.link}>Retake</Text></Pressable></View>)}<Pressable disabled={busy} onPress={submit} style={s.button}><Text style={s.buttonText}>{busy?'Registering…':'Submit & enroll student'}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7fb'},page:{padding:24,paddingBottom:44},back:{color:'#4169c8',fontWeight:'700',marginBottom:24},kicker:{fontSize:11,letterSpacing:1.5,fontWeight:'800',color:'#4169c8',marginBottom:8},h1:{fontSize:30,fontWeight:'800',color:'#10203b',marginBottom:7},muted:{fontSize:14,color:'#71809a',lineHeight:21},field:{marginTop:17},label:{fontSize:13,fontWeight:'700',color:'#34445d',marginBottom:7},input:{height:50,borderRadius:12,borderWidth:1,borderColor:'#dce3ee',backgroundColor:'#fff',paddingHorizontal:15,color:'#15233a'},button:{backgroundColor:'#1d4ed8',borderRadius:13,minHeight:50,alignItems:'center',justifyContent:'center',paddingHorizontal:18,marginTop:20},buttonText:{color:'#fff',fontWeight:'800'},disabled:{opacity:.45},camera:{height:360,borderRadius:24,overflow:'hidden',marginTop:24,backgroundColor:'#172640',position:'relative'},preview:{width:'100%',height:'100%'},oval:{position:'absolute',left:'22%',top:15,width:'56%',height:330,borderWidth:3,borderColor:'#8fb0ff',borderRadius:180},guidance:{backgroundColor:'#fff',borderRadius:15,padding:16,marginTop:14,fontSize:16,fontWeight:'800',color:'#1d4ed8'},secondary:{borderRadius:13,minHeight:50,alignItems:'center',justifyContent:'center',paddingHorizontal:18,marginTop:14,backgroundColor:'#e9efff'},secondaryText:{color:'#2854b4',fontWeight:'800'},row:{flexDirection:'row',alignItems:'center',backgroundColor:'#fff',padding:10,marginTop:10,borderRadius:14,gap:12},thumb:{width:56,height:56,borderRadius:10},rowText:{fontWeight:'800',color:'#1b2c46',flex:1},link:{color:'#1d4ed8',fontWeight:'700'}});
